export const categoriesIcons = {
    "categoriesWithIcons": [
        { category: "Groceries", icon: "cart-outline" },
        { category: "Transportation", icon: "bus-outline" },
        { category: "Health", icon: "medkit-outline" },
        { category: "Education", icon: "school-outline" },
        { category: "Shopping", icon: "pricetag-outline" },
        { category: "Travel", icon: "airplane-outline" },
        { category: "Entertainment", icon: "film-outline" },
        { category: "Dining", icon: "restaurant-outline" },
        { category: "Rent", icon: "home-outline" },
        { category: "Utilities", icon: "flash-outline" },
        { category: "Insurance", icon: "shield-checkmark-outline" },
        { category: "Fitness", icon: "fitness-outline" },
        { category: "Investments", icon: "trending-up-outline" },
        { category: "Salary", icon: "cash-outline" },
        { category: "Gifts", icon: "gift-outline" },
        { category: "Donations", icon: "heart-outline" },
        { category: "Loans", icon: "wallet-outline" },
        { category: "Savings", icon: "piggy-bank-outline" },
        { category: "Subscriptions", icon: "newspaper-outline" },
        { category: "Phone", icon: "call-outline" },
        { category: "Internet", icon: "wifi-outline" },
        { category: "Clothing", icon: "shirt-outline" },
        { category: "Beauty", icon: "rose-outline" },
        { category: "Personal Care", icon: "body-outline" },
        { category: "Childcare", icon: "baby-outline" },
        { category: "Pets", icon: "paw-outline" },
        { category: "Cleaning", icon: "broom-outline" },
        { category: "Home Maintenance", icon: "construct-outline" },
        { category: "Repairs", icon: "hammer-outline" },
        { category: "Furniture", icon: "bed-outline" },
        { category: "Electronics", icon: "laptop-outline" },
        { category: "Books", icon: "book-outline" },
        { category: "Music", icon: "musical-notes-outline" },
        { category: "Movies", icon: "videocam-outline" },
        { category: "Games", icon: "game-controller-outline" },
        { category: "Software", icon: "code-outline" },
        { category: "Hobbies", icon: "color-palette-outline" },
        { category: "Toys", icon: "cube-outline" },
        { category: "Events", icon: "calendar-outline" },
        { category: "Charity", icon: "hand-heart-outline" },
        { category: "Memberships", icon: "card-outline" },
        { category: "Business", icon: "briefcase-outline" },
        { category: "Freelance", icon: "document-outline" },
        { category: "Side Jobs", icon: "hammer-outline" },
        { category: "Bonus", icon: "trophy-outline" },
        { category: "Freight", icon: "train-outline" },
        { category: "Taxis", icon: "car-outline" },
        { category: "Ride Sharing", icon: "car-sport-outline" },
        { category: "Public Transport", icon: "subway-outline" },
        { category: "Fuel", icon: "gas-outline" },
        { category: "Parking", icon: "stop-outline" },
        { category: "Car Maintenance", icon: "car-wash-outline" },
        { category: "Tolls", icon: "road-outline" },
        { category: "Bicycles", icon: "bicycle-outline" },
        { category: "Motorcycles", icon: "motorcycle-outline" },
        { category: "Flights", icon: "airplane-outline" },
        { category: "Hotels", icon: "bed-outline" },
        { category: "Vacation", icon: "umbrella-outline" },
        { category: "Cruises", icon: "boat-outline" },
        { category: "Camping", icon: "camp-outline" },
        { category: "Hiking", icon: "walk-outline" },
        { category: "Tours", icon: "map-outline" },
        { category: "Adventure", icon: "planet-outline" },
        { category: "Photography", icon: "camera-outline" },
        { category: "Video", icon: "videocam-outline" },
        { category: "Social Media", icon: "chatbox-outline" },
        { category: "Streaming", icon: "tv-outline" },
        { category: "Sports", icon: "football-outline" },
        { category: "Gym", icon: "barbell-outline" },
        { category: "Yoga", icon: "flower-outline" },
        { category: "Cycling", icon: "bicycle-outline" },
        { category: "Running", icon: "walk-outline" },
        { category: "Swimming", icon: "water-outline" },
        { category: "Martial Arts", icon: "fist-outline" },
        { category: "Boxing", icon: "glove-outline" },
        { category: "Fishing", icon: "fish-outline" },
        { category: "Hunting", icon: "disc-outline" },
        { category: "Diving", icon: "disc-outline" },
        { category: "Skiing", icon: "snow-outline" },
        { category: "Surfing", icon: "wave-outline" },
        { category: "Boating", icon: "boat-outline" },
        { category: "Sailing", icon: "boat-outline" },
        { category: "Horse Riding", icon: "horse-outline" },
        { category: "Archery", icon: "disc-outline" },
        { category: "Shooting", icon: "disc-outline" },
        { category: "Wrestling", icon: "body-outline" },
        { category: "Basketball", icon: "basketball-outline" },
        { category: "Baseball", icon: "baseball-outline" },
        { category: "Soccer", icon: "football-outline" },
        { category: "Golf", icon: "golf-outline" },
        { category: "Tennis", icon: "tennisball-outline" },
        { category: "Rugby", icon: "american-football-outline" },
        { category: "Volleyball", icon: "volleyball-outline" },
        { category: "Cricket", icon: "cricket-outline" },
        { category: "Racing", icon: "flag-outline" },
        { category: "Concerts", icon: "mic-outline" },
        { category: "Theater", icon: "people-outline" },
        { category: "Festivals", icon: "disc-outline" },
        { category: "Parties", icon: "wine-outline" },
        { category: "Exhibitions", icon: "color-palette-outline" }
      ]
}